name: validator

on:
  pull_request:
    paths:
      - "validator/**"
      - ".github/workflows/**"
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run formatter, linter and import sorting.
        run: npm run check --workspace=validator

      - name: Run tests with coverage
        run: npm run test --workspace=validator
